services:
  cron:
    image: "cron:latest"
    ports:
      - "3001:3001"
    working_dir: /opt/app
    container_name: cron

  #frontend-app:
  #  #image: "ghcr.io/developkosarev/frontolservicenext:latest"
  #  image: "my-new-app:nx-container"
  #  ports:
  #      - "3001:3001"
  #  working_dir: /opt/app
  #  container_name: my-new-app
