services:
  cron:
    build:
      context: .
      dockerfile: apps/cron/Dockerfile-dev
      target: development
    container_name: cron
    command: npx nx run cron:serve
    env_file:
      - ./apps/cron/.env
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app

  #cron:
  #  image: "cron:latest"
  #  ports:
  #    - "3001:3001"
  #  working_dir: /opt/app
  #  container_name: cron

  #frontend-app:
  #  #image: "ghcr.io/developkosarev/frontolservicenext:latest"
  #  image: "my-new-app:nx-container"
  #  ports:
  #      - "3001:3001"
  #  working_dir: /opt/app
  #  container_name: my-new-app

  rabbitmq:
    build: images/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: images/env/rabbitmq.env

volumes:
  rabbitmqdata:
