services:
  cron:
    image: "ghcr.io/developkosarev/cron-next:v0.0.1"
    ports:
      - "3001:3001"
    working_dir: /opt/app
    container_name: cron

  rabbitmq:
    build: images/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: images/env/rabbitmq.env

volumes:
  rabbitmqdata:
