version: "3.8"
services:
  frontend-app:
    #image: "ghcr.io/developkosarev/frontolservicenext:latest"
    image: "my-new-app:nx-container"
    ports:
        - "3000:3000"
    working_dir: /opt/app
    container_name: my-new-app
